java.lang.InterruptedException 中断异常只有在阻塞的情况下才会发生，比如调用了wait、join。   
ThreadA调用了wait()或者join()被阻塞，其他线程中执行ThreadA.interrupt()会出发ThreadA的中断异常。   
如果ThreadA未阻塞，则只是结束，不报异常。   

线程通信机制：  
wait 和 notify  必须在同步块中使用，或者说使用该方法时必须获得了共享对象的锁。
wait会释放获得的锁，进入对象的阻塞队列，notify会释放锁，唤醒某一个阻塞的线程，notifyAll会唤醒所有阻塞线程。
在有n个线程阻塞，调用notify需要调用n次才能保证阻塞线程全部唤醒并继续执行，但如果调用notifyAll只需要调用一次即可，虽然调用了notifyAll后多个线程竞争同一把锁，只有一个线程，比如b拿到，但在b执行结束后不需要唤醒线程，因为线程已经是唤醒的，在b结束后会继续竞争锁。

notify执行结束后并不会立刻释放锁，会在同步代码块执行结束后才释放。